### PR TITLE
Updated list of attributes

### PR DESCRIPTION
**Pull request by pemcg**
Added 4 new attributes which will help identify which workloads are unsuitable for migration to CNV

### CODE REVIEW

**Comment by pemcg** [comment]
@miq-bot add_label enhancement Ivanchuk/yes

**Comment by pemcg** [comment]
@miq-bot add_label enhancement

**Comment by pemcg** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by mturley** [comment]
@pemcg do we already have a bugzilla issue open for this which targets an ivanchuk release?

**Comment by pemcg** [comment]
@mturley yes, it's https://bugzilla.redhat.com/show_bug.cgi?id=1798054

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit c8dc5f07987d4f9018a09dce9cd466241297d4ce
Author: Adam Grare <agrare@redhat.com>
Date:   Tue Feb 4 08:36:11 2020 -0500

    Merge pull request #39 from pemcg/add_cnv_flag_attributes_to_manifest

    Updated list of attributes

    (cherry picked from commit 754df8a2c8a7d5ac3bffe367d8e9930deba85f08)

    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1805813
```

**Pull request merged**
