### PR TITLE
Put the payload in public/migration_analytics

### PR DESCRIPTION
**Pull request by agrare**
Allow the tgz to be downloaded from the webserver by placing it in the
public/ directory.

Depends on: ~~https://github.com/RedHatCloudForms/cfme-cloud_services/pull/42~~

### CODE REVIEW

**Comment by agrare** [comment]
cc @abellotti @Fryguy 

This puts the payload files in `/var/www/miq/vmdb/public/migration_analytics`, I'm open to other locations though if there is someplace better.  This has the downside (compared to /tmp) of not being automatically cleaned up, but the upside that it doesn't have to use the API to download the file.

**Comment by mturley** [comment]
@abellotti I see that we have the full path of the file in `task.context_data.payload_path`. Once we get the file placed in public/migration_analytics, is that payload_path going to be sufficient for the UI to determine the full download URL it should use? It would be nice if we can also put a `payload_url` property into `context_data` that the UI can just display directly to eliminate any issues with constructing that URL.

**Comment by bthurber** [comment]
Cleanup is the one thing to consider longer term.  We don't plan to GA this feature until CF 5.1 so we will have some time to work on that.  This also really only applies to the disconnected use case and we don't expect a large number of these payload files to be generated if that helps in the discussion.

**Comment by agrare** [comment]
Once we take the disconnected feature on for CFME proper we'll add a scheduled task to cleanup these types of files.

**Comment by bthurber** [comment]
> Once we take the disconnected feature on for CFME proper we'll add a scheduled task to cleanup these types of files.

Sounds great!

**Comment by abellotti** [comment]
@mturley from the full path, you can just extract "/migration_analytics/.*" as the path part for now for the public_url, i.e. https://appliance/migration_analytics/.*

**Comment by mturley** [comment]
Ok @abellotti that works. If you guys think this implementation is good for now, I think I can get everything ready to go end-to-end if we merge it today.

**Comment by mturley** [comment]
Based on the assumption from https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/16#issuecomment-521773111, I implemented the rest of the UI changes: https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/17

**Comment by mturley** [comment]
Since the UI itself is rendered at http://appliance/migration_analytics, I wonder if that will be a conflict. My PR assumes it won't... but that can be changed here: https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/17/files#diff-6da6f9aebb506ed7a5b23b946dc7fa61R3

**Comment by agrare** [comment]
@abellotti are we going to have a conflict on the path name? I'm not able to test with an appliance right now

**Comment by abellotti** [comment]
@agrare yea, looks like with the ui controller.  let's pick another name, and kick the tire on an appliance  before this goes in.

**Comment by mzazrivec** [comment]
@agrare @abellotti Strictly speaking, things are going to work fine this way (i.e. there won't be any conflict in the sense that download & the ui controller won't work). It just looks funny.

**Comment by agrare** [comment]
Okay I was able to download a payload from `https://dhcp-8-99-239.cloudforms.lab.eng.rdu2.redhat.com/migration_analytics/cfme_inventory20190819-1109-1yfmzzu.tar.gz` after manually changing the file permissions to 0644 (it was created with 0600).

I'll push a commit to generate the file with the proper permissions then this should be ready to go.

**Comment by agrare** [comment]
Okay done, now depends on https://github.com/RedHatCloudForms/cfme-cloud_services/pull/42

**Comment by agrare** [comment]
Okay @mzazrivec @abellotti this is ready for review

**Comment by mzazrivec** [comment]
@agrare I can confirm that things are working fine here. The only concern I have are potential security implications of making a file, which contains all kinds of provider information, possible to download by anybody (i.e. without authentication of any kind).

**Comment by agrare** [comment]
Yeah Alberto brought up the same concern, the file path cannot be guessed because it is created by tmpname and the directory can't be browsed so it can't be discovered.  I'd love if we could add some type of auth in front of it but I don't know if it is feasible to get Apache to share the same auth as miq.

**Comment by martinpovolny** [comment]
> Yeah Alberto brought up the same concern, the file path cannot be guessed because it is created by tmpname and the directory can't be browsed so it can't be discovered.

We definitely should add some auth there. Relying on obscurity of the file name is not right.

>  I'd love if we could add some type of auth in front of it but I don't know if it is feasible to get Apache to share the same auth as miq.

That should be doable. Apache comes with a bunch of modules with many different ways of configuring the password backend.

**Comment by agrare** [comment]
@martinpovolny sounds good to me, that's well out of my area of expertise and will take some appliance config changes I assume so I'll leave that to you

**Comment by martinpovolny** [comment]
Not that I do not have a long backlog ;-)

I can imagine using basic auth with custom password backend.

 1. db backend
 1. external auth backend

### DB backend

Searching the first shows me:
https://httpd.apache.org/docs/2.4/mod/mod_authn_dbd.html

but that would require plain passwords. I assume there will be other solutions that would use hashed passwords but it would need to support the same password hashing we have in ManageIQ. @agrare : do you know how we hash passwords?

### External auth backend

using external auth and connecting it to a Ruby script that would connect to our DB using Active Record (and whatever else is needed from Rails).

This seems relevant: libapache2-mod-authnz-external

So we need more inputs:
 1. what hashing do we use?
 1. what apache modules for custom auth are available on the appliance. RHEL 7, righ, @agrare?

**Comment by himdel** [comment]
> do you know how we hash passwords?

I'm seeing `$2a$10$...` in `user`.`password_digest`, so we're using a slightly old version of bcrypt, with 2^10 rounds.

**Comment by martinpovolny** [comment]
Thinking...

If this is to be consumed from the browser where the user is already logged in then

 1. the external auth can be done in such a way that it would accept our cookies (and do the auth).
 1. ... and it can be mapped (using Apache) under the UI URL prefix on the appliance so that the browser would send the cookie.
 1. ... and the external auth process could verify the session if it's present and only fall back to basic auth (or just fail).

**Comment by bthurber** [comment]
@agrare checking in on merge status.  Is security the generated file the hurdle?

**Comment by martinpovolny** [comment]
I have one more question on this piece:

 1. the API created a directory
 1. the API queues a task with a path where to store results
 1. some worker fullfills the task
 1. user via browser is supposed to download the data

How does it work across appliances?

 1. API role does that on it's appliance -- creates the directory.
 1. On a potentially different appliance there's the role that picks up the task. If it's a different appliance the directory will not be there.
 1. On a yet another appliance the UI worker that serves the UI will offer a download from an URL on the appliance where it is running.

Where is the mechanism that ensures that all these 3 things happen on the same appliance?

Is there some special limitation enforced by the V2V usecase that everything runs on the same one?

Am I missing something?

**Comment by agrare** [comment]
@bthurber yes appears so
@martinpovolny  we are going to use the server guid option to MiqQueue to ensure that the work is picked up by the API server.

**Comment by himdel** [comment]
> we are going to use the server guid option to MiqQueue to ensure that the work is picked up by the API server.

@agrare So, this can't be mapped under `/migration_analytics` because that's UiWorker, and has to be mounted somewhere `/api`, right?

**Comment by agrare** [comment]
@himdel it is mapped to `/car/www/miq/vmdb/public/migration_analytics` and is served by Apache not the API server.  I'm open to renaming it if it is confusing

**Comment by martinpovolny** [comment]
> we are going to use the server guid option to MiqQueue to ensure that the work is picked up by the API server.

and the API is going to be the same one as the UI?

**Comment by agrare** [comment]
> and the API is going to be the same one as the UI?

No but I assume that the UI will be able to download a file from the API server.

**Comment by himdel** [comment]
> No but I assume that the UI will be able to download a file from the API server.

That's exactly the problem I think :) It won't.
The only way the UI can access anything physically on the API appliances is via the API.

Or via anything mounted under the API endpoints on the webserver.
The point is, the url has to be /api/foo, because just /foo is on the wrong server.

**Comment by agrare** [comment]
So you're saying if the UI is being served by `1.2.3.4/migration_analytics` and the API is being served by `6.7.8.9/api`, the UI won't be able to build a URL and present it to the user to download something being served up by `6.7.8.9/downloads` which is served by apache?

**Comment by himdel** [comment]
https://github.com/ManageIQ/manageiq-appliance/blob/master/COPY/etc/httpd/conf.d/manageiq-redirects-api#L1

Apache redirects the API to the right place.

**Comment by agrare** [comment]
I'll defer to you @himdel @martinpovolny and @abellotti on this, I tested it on an appliance and it worked, but if what you're saying is true then this needs to be redesigned.

In this case I'm going to tap out on this.  Was just trying to help move this along by implementing a design that @abellotti @mturley and I agreed on.  If it won't work then someone on the UI/API side will need to design it.

**Comment by himdel** [comment]
> the UI is being served by 1.2.3.4/migration_analytics
> the API is being served by 6.7.8.9/api
> the UI won't be able to build a URL and present it to the user to download something being served up by 6.7.8.9/downloads which is served by apache?

I'm saying apache will redirect UI requests (not under /api) to the UI appliance,
and API request to the API appliance.

If the request is to 6.7.8.9/downloads, it will land on 1.2.3.4/downloads, which is not the machine with the data.
If the request is to 1.2.3.4/api, it will land on 6.7.8.9/api, which is the right machine.

**Comment by himdel** [comment]
IMO the best solution would be to store this on the API appliance, and add an proper, authenticated API endpoint that will serve the file from there.

Anything else involves writing separate authentication code, or moving files between appliances.

**Comment by martinpovolny** [comment]
> IMO the best solution would be to store this on the API appliance, and add an proper, authenticated API endpoint that will serve the file from there.

I agree that the cleanest way is to serve it through the API. Because as @himdel wrote anything else requires writing authentication code which is best to avoid (tough to do right).

A note on the idea of not authenticating access to the file: I do not know what is going to be there. Maybe it's not "secret" at this point. But I can imagine that more stuff would be added and we might get into problems.

If all one needs to get some data is the (secret/random) URL then the data should be considered public. URLs can be loggen in in a proxy for example...

**Comment by abellotti** [comment]
For moving this to the API, a couple of questions/points here:

- What kind of file sizes can we expect here ? don't want to block the API too long.
- If we're moving this data in the DB (for access from any API server instance), we might need to do the periodic recycling now so the DB does not grow crazy fast. Heck if it's accessed via the API, one option is zapping after the one access (if that fits the use-case).
- How would this new API be authenticated ?  Don't think we want to embed any creds in the URL. Also, kinda' awkward to provide them a curl for them to run and provide credentials on a CLI.  So maybe this can provided behind a UI page (user logged into UI then access to the resource via API via the browser's api token). This would work with all current ext-auth methods too (including Kerb SSO, SAML, etc).

**Comment by himdel** [comment]
Oh, good point, there can be multiple API appliances.
So, yeah, we may need to put this in the db (eww), or implement static file synchronization accross appliances.

Or we could require the user to provide an endpoint to upload the file to, instead of trying to provide a download link.

(If the db solution wins, yeah, agreed this would need a simple UI landing page that will give you a Download button, to prevent API authentication issues with random links.)

**Comment by bthurber** [comment]
On another note here, for IMS we download log files from the UI and implemented an RBAC function for this.  https://github.com/oVirt/v2v-conversion-host/blob/master/kubevirt-conversion/Dockerfile#L1

The discussion seems to have turned into a bit of boil the ocean.  For the purposes of Migration Analytics we don't require file sync across appliances.  

Finally, the size of the payload files are not statically set.  It depends on the size of the VMware environment and if Smart State Analysis has been run (larger data set captured) or not.  We have Basic and Detailed options for the payload generation.

**Comment by AparnaKarve** [comment]
A couple takeaways from the above discussion -

- Giving public download access to a payload file on an appliance is a NO
- saving the payload in `/tmp` is preferable, but would require an API to download the file
- We *do* need the API or some sort of authentication mechanism, otherwise it's a free public download
- The approach used here https://github.com/ManageIQ/manageiqv2v/blob/master/app/controllers/migration_log_controller.rb would be considered acceptable
-------------
One possible approach would be to keep the payload in `/tmp` and use `send_file` in an API or a controller route, whatever is generally preferred..

Below is an example of how to implement the above using a controller route `/migration_analytics/download_tar`

Backend code -

```rb
def download_tar
  assert_privileges('migration')
  send_file params[:payload]
  #params[:payload] is a file in the /tmp folder e.g. /tmp/cfme_inventory-20190821-3380-1l1d18q.tar.gz
end
```

JS code -
```js
const downloadPayload = `/migration_analytics/download_tar?payload=${payloadPath}`;
...
...
<Button bsStyle="primary" href={downloadPayload} disabled={!payloadUrl}>
```

-----

@agrare What do you think of this approach?

**Comment by mzazrivec** [comment]
> ```ruby
> def download_tar
>   assert_privileges('migration')
>   send_file params[:payload]
>   #params[:payload] is a file in the /tmp folder e.g. /tmp/cfme_inventory-20190821-3380-1l1d18q.tar.gz
> end
> ```

I don't think so. This would create even a bigger security problem, since you're in fact exposing the whole filesystem for download here.

**Comment by martinpovolny** [comment]
I think that the most important question is what @abellotti asked:

> What kind of file sizes can we expect here ? don't want to block the API too long.

Do we have some range? Who can tell?

**Comment by bthurber** [comment]
> I think that the most important question is what @abellotti asked:
> 
> > What kind of file sizes can we expect here ? don't want to block the API too long.
> 
> Do we have some range? Who can tell?
> 
> Because that will tell us if we can download through the API or we need just the authentication piece and download via Apache w/o Ruby being in the loop.
> 
> Then we can discuss if it needs to live with the API or the UI.

A large VMware env with 10K VM's, payload is less than 1MB in .tgz format.

**Comment by martinpovolny** [comment]
> A large VMware env with 10K VM's, payload is less than 1MB in .tgz format.

@abellotti : do you think that if the size is limited to let's say 5MB is't ok to go through the API?

**Comment by AparnaKarve** [comment]
> I don't think so. This would create even a bigger security problem, since you're in fact exposing the whole filesystem for download here.

Funny, I knew somebody would say that :)

... precisely why I also posted the other `send_file` code above

```rb
# or the approach below where we retrieve the filename via the task_id

def download_tar
  assert_privileges('migration')
  task = MiqTask.find(params[:task_id])
  file = task.context_data[:payload_path]
  send_file file
end
```

This is a roundabout way of downloading the payload file via the task_id

The location for the payload would be acquired via the task_id, which is a good deterrent for any malicious user. 
Also a user who has access to 'migration' (via `assert_privileges('migration')` RBAC) cannot be technically considered malicious.

`send_file`/`send_data` can be used responsibly as shown above, and would get the job done.
As a matter of fact, it has been extensively used in other areas of the UI for downloading CSVs, TXT, PDF files.

**Comment by martinpovolny** [comment]
@AparnaKarve, I think that @mzazrivec was commenting about the `send_file params[:payload]` (the important being the argument coming from unsafe source) and I am sure that the example can be safeguarded to do right/safely. And yes, we have places in the code where we do such things. 

But that is rather orthogonal to the issues we have here. I do not think we have a problem sending a file.

 1. We need to deal with the concern that sending a big file may potentially block the API (or the UI).

 2. And we need to make sure that the file is placed and located on the appliance that is running the worker (API or UI) that would be actually sending the file.

**Comment by AparnaKarve** [comment]
> I think that @mzazrivec was commenting about the send_file params[:payload] (the important being the argument coming from unsafe source) and I am sure that the example can be safeguarded to do right/safely.

@martinpovolny 
Agreed about the pitfalls of using ` params[:payload]` -- hence the second option, which does not have ` params[:payload]`  was also mentioned above.

I would assume that `send_file` is a threaded operation to prevent it from blocking the API/UI -- because it's really the Ruby/Rails solution to download files in general.

IMO send_file should work without issues.
Anyway, I leave it to you to come up with the right solution.
Thanks.

**Pull request closed without merging**
