### PR TITLE
Run inventory bundle action, poll for completion, and display payload path and working download button

### PR DESCRIPTION
**Pull request by mturley**
This PR completes the end-to-end data collection in the Migration Analytics UI.

Based on @abellotti's comment (https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/16#issuecomment-521773111) this code assumes that the `task.context_data.payload_path` will contain the substring `/migration_analytics/`, and if so it creates a root-relative URL using everything that follows that substring, e.g. `/migration_analytics/some/path/payload.tgz`.

The correct number of VMs, payload path, and working download button are then rendered on the completion screen:

Screenshot 2019-08-15 17 42 29

If the `payload_path` does not contain that `/migration_analytics/` substring (as it currently does not on master, since #16 is not merged as I write this), the download button will be disabled and read "Download Not Available", but the path will still be displayed:

Screenshot 2019-08-15 17 30 25

If there are any errors in the request that starts the bundle, or in the bundle task itself, they will be displayed in an empty state with a Cancel button that returns the user to the provider selection screen:

Screenshot 2019-08-15 22 33 26

So, we can merge this ahead of #16 and everything Should Just Work ™️ when that PR is merged. @mzazrivec @AparnaKarve @agrare I think we should go ahead and review/merge this, and then double back to test everything after #16 is merged, and make a follow-up PR if necessary to fix it.

Note: I did not end up finding time today to write new unit tests for the code in this PR, I think we can handle that in another PR. @mzazrivec @AparnaKarve if you'd like to do that, be my guest, otherwise I'll do it when I get back on the 26th. I did fix/update the existing tests that I broke, though.

I'm headed overseas, thanks for the help and good luck all🍹

### CODE REVIEW

**Comment by mturley** [comment]
Since the UI itself is rendered at http://appliance/migration_analytics, I wonder if that will be a conflict. This PR assumes it won't... but that can be changed here: https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/17/files#diff-6da6f9aebb506ed7a5b23b946dc7fa61R3

**Comment by mturley** [comment]
I fixed the rendering of errors, which was my last TODO that I forgot about earlier today. Leaving for PTO for reals this time.

**Comment by mzazrivec** [comment]
I'm going to merge this PR in its current form and will create a new PR implementing an alternative way of downloading created payload, since https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/16 hasn't been merged in its current form.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 4e0d2cca5ddbc95b0079211efabee3d49d4bc0ec
Author: Milan Zázrivec <mzazrivec@redhat.com>
Date:   Fri Aug 23 11:32:04 2019 +0200

    Merge pull request #17 from mturley/actually-call-bundle-from-ui-this-time
    
    Run inventory bundle action, poll for completion, and display payload path and working download button
    
    (cherry picked from commit 173c4d12246402a1ee7cda98d4a4ee3c7402a67e)
```

**Pull request merged**
